# Generated by Django 4.1.2 on 2022-12-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_proceure_post_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
