# Generated by Django 4.1.2 on 2022-11-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_proceure_post_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
